name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  # will run tests
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Set up node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm i
      # - name: Run tests
      #   run: npm test

  # Will be triggered, if build passes
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Set up node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm i
      - name: Build artifact
        run: npm run build
      - name: Build type declarations
        run: ./node_modules/typescript/bin/tsc
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: npm version patch --force
      - run: git push --tags && git push
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
